# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_fil_name', models.CharField(max_length=30)),
                ('all_fil_upload_from_user', models.CharField(max_length=500, null=True)),
                ('all_fil_text', models.TextField(null=True)),
                ('all_fil_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='文件上传日期')),
                ('all_file', models.FileField(null=True, upload_to='./uploads/all', verbose_name='文件')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ann_text', models.TextField(null=True)),
                ('ann_title', models.CharField(max_length=50, null=True)),
                ('ann_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='公告发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_text', models.CharField(max_length=512, null=True)),
                ('ans_read', models.BooleanField(default=False)),
                ('ans_from_user', models.CharField(max_length=500, null=True)),
                ('ans_to_user', models.CharField(max_length=500, null=True)),
                ('ans_send_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='answer question')),
                ('ans_que_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.CharField(max_length=128, unique=True)),
                ('cus_name', models.CharField(default='未实名认证', max_length=128)),
                ('cus_major', models.CharField(default='未选择专业', max_length=128)),
                ('cus_college', models.CharField(default='未选择学院', max_length=128)),
                ('cus_password', models.CharField(max_length=256)),
                ('cus_email', models.EmailField(max_length=254, unique=True)),
                ('cus_sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('cus_join_time', models.DateTimeField(auto_now_add=True)),
                ('cus_role', models.CharField(choices=[('student', '学生'), ('teacher', '老师'), ('administrator', '管理员')], default='学生', max_length=20)),
                ('cus_urge', models.BooleanField(default=False)),
                ('cus_project_file', models.BooleanField(default=False)),
                ('cus_project_id', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_text', models.CharField(max_length=512, null=True)),
                ('eva_from_user', models.CharField(max_length=500, null=True)),
                ('eva_to_user', models.CharField(max_length=500, null=True)),
                ('eva_send_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='answer question')),
            ],
        ),
        migrations.CreateModel(
            name='Journalism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jou_text', models.TextField(null=True)),
                ('jou_title', models.CharField(max_length=50, null=True)),
                ('jou_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='新闻发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_from_user', models.CharField(max_length=500, null=True)),
                ('pro_from_user_id', models.CharField(max_length=500, null=True)),
                ('pro_text', models.TextField(null=True)),
                ('pro_title', models.CharField(max_length=50, null=True)),
                ('pro_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='课题发布日期')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_fil_upload_to_user', models.CharField(max_length=500, null=True)),
                ('pro_fil_name', models.CharField(max_length=30)),
                ('pro_fil_upload_from_user', models.CharField(max_length=500, null=True)),
                ('pro_fil_pro_id', models.IntegerField(null=True)),
                ('pro_fil_text', models.TextField(null=True)),
                ('pro_fil_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='文件上传日期')),
                ('pro_file', models.FileField(null=True, upload_to='./uploads/projects', verbose_name='文件')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_text', models.CharField(max_length=512, null=True)),
                ('que_read', models.BooleanField(default=False)),
                ('que_from_user', models.CharField(max_length=500, null=True)),
                ('que_to_user', models.CharField(max_length=500, null=True)),
                ('que_send_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ask question')),
                ('que_replay', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_text', models.TextField(null=True)),
                ('reg_title', models.CharField(max_length=50, null=True)),
                ('reg_pub_date', models.DateTimeField(auto_now_add=True, verbose_name='规定发布日期')),
            ],
        ),
    ]
